# Generated by Django 6.0.7 on 2026-07-14 21:19

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'eps',
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('capacidad_diaria', models.PositiveIntegerField(default=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Especialidades',
                'db_table': 'especialidad',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='especialidad_nombre_ci_unique')],
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_medico', models.CharField(max_length=50, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('especialidades', models.ManyToManyField(related_name='medicos', to='pacientes.especialidad')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'medico',
            },
        ),
        migrations.CreateModel(
            name='ExcepcionMedico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excepciones', to='pacientes.medico')),
            ],
            options={
                'db_table': 'excepcion_medico',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('tipo_cita', models.CharField(default='consulta_general', max_length=30)),
                ('notificacion_encolada', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('eps', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pacientes.eps')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.especialidad')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pacientes.medico')),
            ],
            options={
                'db_table': 'cita',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='NotificacionPendiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('confirmacion_cita', 'Confirmación de cita')], max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('enviada', 'Enviada'), ('fallida', 'Fallida')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='pacientes.cita')),
            ],
            options={
                'db_table': 'notificacion_pendiente',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PASAPORTE', 'Pasaporte')], max_length=20)),
                ('num_documento', models.CharField(max_length=30, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('eps', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pacientes.eps')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'paciente',
            },
        ),
        migrations.AddField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='pacientes.paciente'),
        ),
        migrations.CreateModel(
            name='TopeEPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_citas', models.PositiveIntegerField(help_text='Número máximo de citas permitidas')),
                ('tipo_periodo', models.CharField(choices=[('SEMANAL', 'Semanal'), ('MENSUAL', 'Mensual')], default='MENSUAL', max_length=10)),
                ('presupuesto_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('eps', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tope', to='pacientes.eps')),
            ],
            options={
                'verbose_name_plural': 'Topes EPS',
                'db_table': 'tope_eps',
            },
        ),
        migrations.CreateModel(
            name='HorarioMedico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('max_citas_por_hora', models.PositiveIntegerField(default=4)),
                ('activo', models.BooleanField(default=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='pacientes.medico')),
            ],
            options={
                'db_table': 'horario_medico',
                'constraints': [models.CheckConstraint(condition=models.Q(('hora_inicio__lt', models.F('hora_fin'))), name='horario_medico_inicio_lt_fin')],
            },
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['medico', 'fecha', 'hora_inicio'], name='cita_med_fecha_inicio_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['especialidad', 'fecha'], name='cita_esp_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['eps', 'estado'], name='cita_eps_estado_idx'),
        ),
    ]
