# Generated by Django 6.0.7 on 2026-07-15 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidad',
            name='dias_entre_citas',
            field=models.PositiveIntegerField(default=7, help_text='Cantidad mínima de días entre citas de la misma especialidad para un paciente.'),
        ),
    ]
