# Generated by Django 5.2.8 on 2026-07-15 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excepcionmedico',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excepciones_medicas', to='pacientes.medico'),
        ),
        migrations.CreateModel(
            name='ExcepcionHorario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('tipo', models.CharField(choices=[('BLOQUEO', 'Bloqueo'), ('EXTRA', 'Horario Extra')], max_length=10)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excepciones_horario', to='pacientes.medico')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Día 0'), (1, 'Día 1'), (2, 'Día 2'), (3, 'Día 3'), (4, 'Día 4'), (5, 'Día 5'), (6, 'Día 6')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('max_citas_por_hora', models.PositiveIntegerField(default=4)),
                ('activo', models.BooleanField(default=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_base', to='pacientes.medico')),
            ],
            options={
                'unique_together': {('medico', 'dia_semana')},
            },
        ),
    ]
