# Generated by Django 5.2.8 on 2026-07-14 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_especialidad_alter_eps_id_alter_paciente_id_medico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopeEPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_citas', models.PositiveIntegerField(help_text='Número máximo de citas permitidas')),
                ('tipo_periodo', models.CharField(choices=[('SEMANAL', 'Semanal'), ('MENSUAL', 'Mensual')], default='MENSUAL', max_length=10)),
                ('presupuesto_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('eps', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tope', to='pacientes.eps')),
            ],
            options={
                'verbose_name_plural': 'Topes EPS',
                'db_table': 'tope_eps',
            },
        ),
    ]
