# Generated by Django 5.2.8 on 2026-07-15 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_alter_excepcionmedico_medico_excepcionhorario_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HorarioBase',
        ),
    ]
