# Generated by Django 6.0.7 on 2026-07-14

import django.db.models.functions.text
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_topeeps'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidad',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='especialidad',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='especialidad',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AddConstraint(
            model_name='especialidad',
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower('nombre'),
                name='especialidad_nombre_ci_unique',
            ),
        ),
    ]
