# Generated by Django 6.0.7 on 2026-07-15 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_especialidad_dias_entre_citas'),
        ('pacientes', '0003_delete_horariobase'),
    ]

    operations = [
    ]
