# Generated by Django 6.0.7 on 2026-07-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_merge_20260715_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='recordatorio_enviado',
            field=models.BooleanField(default=False, help_text='Indica si ya se encoló el recordatorio de 24h para esta cita.'),
        ),
        migrations.AlterField(
            model_name='notificacionpendiente',
            name='tipo',
            field=models.CharField(choices=[('confirmacion_cita', 'Confirmación de cita'), ('cancelacion_cita', 'Cancelación de cita'), ('reprogramacion_cita', 'Reprogramación de cita'), ('recordatorio_cita', 'Recordatorio de cita (24h)')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['paciente', '-fecha_hora'], name='cita_paciente_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacionpendiente',
            index=models.Index(condition=models.Q(('estado', 'pendiente')), fields=['estado'], name='notif_pendiente_idx'),
        ),
    ]
