# Generated by Django 6.0.7 on 2026-07-14 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_especialidad_activo_fechas_y_restricciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcepcionMedico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'excepcion_medico',
            },
        ),
        migrations.CreateModel(
            name='HorarioMedico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('max_citas_por_hora', models.PositiveIntegerField(default=4)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'horario_medico',
            },
        ),
        migrations.CreateModel(
            name='NotificacionPendiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('confirmacion_cita', 'Confirmación de cita')], max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('enviada', 'Enviada'), ('fallida', 'Fallida')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notificacion_pendiente',
            },
        ),
        migrations.AddField(
            model_name='cita',
            name='eps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pacientes.eps'),
        ),
        migrations.AddField(
            model_name='cita',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='notificacion_encolada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cita',
            name='tipo_cita',
            field=models.CharField(default='consulta_general', max_length=30),
        ),
        migrations.AddField(
            model_name='especialidad',
            name='capacidad_diaria',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['medico', 'fecha', 'hora_inicio'], name='cita_med_fecha_inicio_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['especialidad', 'fecha'], name='cita_esp_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['eps', 'estado'], name='cita_eps_estado_idx'),
        ),
        migrations.AddField(
            model_name='excepcionmedico',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excepciones', to='pacientes.medico'),
        ),
        migrations.AddField(
            model_name='horariomedico',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='pacientes.medico'),
        ),
        migrations.AddField(
            model_name='notificacionpendiente',
            name='cita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='pacientes.cita'),
        ),
        migrations.AddConstraint(
            model_name='horariomedico',
            constraint=models.CheckConstraint(condition=models.Q(('hora_inicio__lt', models.F('hora_fin'))), name='horario_medico_inicio_lt_fin'),
        ),
    ]
