# Generated by Django 6.0.7 on 2026-07-15 19:10
# HU-022: registro de alertas de tope EPS ya enviadas a superadministrador.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_cita_recordatorio_enviado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaTopeEnviada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('porcentaje_uso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('eps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_tope', to='pacientes.eps')),
            ],
            options={
                'db_table': 'alerta_tope_eps',
                'ordering': ['-creado_en'],
                'constraints': [models.UniqueConstraint(fields=('eps', 'periodo_inicio'), name='alerta_tope_eps_periodo_unique')],
            },
        ),
    ]
