# Generated by Django 6.0.7 on 2026-07-16 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_merge_20260715_0049'),
        ('pacientes', '0005_cita_recordatorio_enviado_and_more'),
    ]

    operations = [
    ]
