# Generated by Django 6.0.7 on 2026-07-15 19:10
# HU-023: configuraciones globales del sistema (horarios institucionales,
# sedes y feriados).

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_alertatopeenviada'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGlobal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_apertura', models.TimeField(default=datetime.time(7, 0))),
                ('horario_cierre', models.TimeField(default=datetime.time(19, 0))),
                ('anticipacion_minima_horas', models.PositiveIntegerField(default=1, help_text='Horas mínimas de anticipación requeridas para poder agendar una cita.')),
                ('anticipacion_maxima_dias', models.PositiveIntegerField(default=90, help_text='Días máximos hacia el futuro en los que se puede agendar una cita.')),
                ('contacto_soporte_email', models.EmailField(blank=True, max_length=254)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'configuracion_global',
            },
        ),
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('descripcion', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Feriados',
                'db_table': 'feriado',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Sedes',
                'db_table': 'sede',
                'ordering': ['nombre'],
            },
        ),
    ]
