# Generated by Django 6.0.7 on 2026-07-16 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_merge_20260715_2026'),
        ('pacientes', '0007_configuracionglobal_feriado_sede'),
    ]

    operations = [
    ]
