# Generated by Django 6.0.7 on 2026-07-16 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_merge_20260715_0049'),
        ('pacientes', '0007_configuracionglobal_feriado_sede'),
    ]

    operations = [
    ]
