# Generated by Django 6.0.7 on 2026-07-16 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0008_merge_20260716_0330'),
        ('pacientes', '0008_paciente_telefono'),
    ]

    operations = [
    ]
