# Generated by Django 5.2.8 on 2026-07-17 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0009_medico_autorizacion_administrativo'),
        ('pacientes', '0009_merge_0008_merge_20260716_0330_0008_paciente_telefono'),
    ]

    operations = [
    ]
