import { useCallback, useEffect, useState } from "react";
import { TopBar, DashboardNav, DashboardBackground, navMobilePadding, EstadoBadge, DashboardStyles } from "../../context/ui";
import { useAuth } from "../../context/AuthContext";
import { cargarCitas, cargarMedicos } from "../../api/admin";
import { extraerMensajeError } from "../../api/axiosClient";
import TabCitas from "./AdminCitas";
import { TabMedicos, TabEspecialidades } from "./AdminMedicosEspecialidades";
import TabPacientes from "./AdminPacientes";
import TabReportes from "./AdminReportes";
import SolicitudesPendientes from "../superadmin/SolicitudesPendientes";

const TABS = [
  { id: "inicio", label: "Dashboard", icon: "dashboard" }, { id: "citas", label: "Citas", icon: "calendar_month" },
  { id: "medicos", label: "Médicos", icon: "stethoscope" }, { id: "especialidades", label: "Especialidades", icon: "medical_information" },
  { id: "pacientes", label: "Pacientes", icon: "groups" }, { id: "solicitudes", label: "Solicitudes", icon: "how_to_reg" }, { id: "reportes", label: "Reportes", icon: "bar_chart" },
];
export const ESTADOS_CITA = ["agendada", "reprogramada", "completada", "cancelada"];
export const ESTADO_ACCENT = { agendada: { color: "#0E9668", tinte: "#D3F3E6" }, reprogramada: { color: "#8A6D00", tinte: "#F5EEDA" }, completada: { color: "#48605C", tinte: "#EDF2F1" }, cancelada: { color: "#BA1A1A", tinte: "#FFDAD6" } };
export const ESTADO_ICONO = { agendada: "event_available", reprogramada: "update", completada: "task_alt", cancelada: "cancel" };
export const capitalizarPrimera = (str) => str ? str.charAt(0).toUpperCase() + str.slice(1) : str;
const hoyISO = () => new Date().toISOString().slice(0, 10);

export function StatCard({ icon, valor, etiqueta, color, tinte, truncar }) { return <div className="bg-white border border-[#DCE8E5] rounded-2xl p-5 flex items-center gap-4"><span className="flex items-center justify-center w-11 h-11 rounded-full shrink-0" style={{ backgroundColor: tinte, color }}><span className="material-symbols-outlined text-xl">{icon}</span></span><div className="min-w-0"><p className={`sax-display text-xl text-[#0F3D3E] ${truncar ? "truncate" : ""}`}>{valor}</p><p className="text-xs text-[#48605C] uppercase tracking-wide">{etiqueta}</p></div></div>; }
export function FilaCitaResumen({ cita }) { const acc = ESTADO_ACCENT[cita.estado] ?? ESTADO_ACCENT.agendada; return <div className="flex items-center justify-between bg-white border border-[#DCE8E5] rounded-xl px-4 py-3"><div className="flex items-center gap-3 min-w-0"><span className="sax-mono text-sm font-semibold shrink-0" style={{ color: acc.color }}>{cita.hora}</span><div className="min-w-0"><p className="font-semibold text-[#0F3D3E] text-sm truncate">{cita.pacienteNombre} · {cita.especialidad}</p><p className="text-xs text-[#48605C] truncate">Dr(a). {cita.medicoNombre} · {cita.sede}</p></div></div><EstadoBadge estado={cita.estado} /></div>; }

export default function AdminDashboard() {
  const { user: admin } = useAuth(); const [tab, setTab] = useState("inicio"); const [citas, setCitas] = useState([]); const [medicos, setMedicos] = useState([]); const [error, setError] = useState("");
  const recargar = useCallback(async () => { try { setError(""); const [c, m] = await Promise.all([cargarCitas(), cargarMedicos()]); setCitas(c); setMedicos(m); } catch (e) { setError(extraerMensajeError(e, "No fue posible cargar los datos administrativos.")); } }, []);
  useEffect(() => { recargar(); }, [recargar]);
  return <div className="min-h-screen bg-[#FBFDFC] text-[#1A2624]"><DashboardBackground /><DashboardStyles /><TopBar nombre={`${admin.nombre} ${admin.apellido}`} /><div className={`max-w-[1200px] mx-auto px-4 md:px-8 py-8 flex flex-col md:flex-row gap-8 ${navMobilePadding}`}><DashboardNav tabs={TABS} activo={tab} onChange={setTab} /><main className="flex-1 min-w-0">{error && <p className="mb-4 text-sm text-[#BA1A1A] bg-[#FFDAD6] px-3 py-2 rounded-lg">{error}</p>}{tab === "inicio" && <TabInicio citas={citas} medicos={medicos} onIrACitas={() => setTab("citas")} />}{tab === "citas" && <TabCitas citas={citas} onCambio={recargar} />}{tab === "medicos" && <TabMedicos citas={citas} onCambio={recargar} />}{tab === "especialidades" && <TabEspecialidades />}{tab === "pacientes" && <TabPacientes citas={citas} onCambio={recargar} />}{tab === "solicitudes" && <SolicitudesPendientes />}{tab === "reportes" && <TabReportes citas={citas} />}</main></div></div>;
}
function TabInicio({ citas, medicos, onIrACitas }) { const hoy = hoyISO(); const citasHoy = citas.filter((c) => c.fecha === hoy); const conteo = Object.fromEntries(ESTADOS_CITA.map((x) => [x, citasHoy.filter((c) => c.estado === x).length])); const activas = citas.filter((c) => ["agendada", "reprogramada"].includes(c.estado)).length; const top = Object.entries(citas.reduce((r, c) => ({ ...r, [c.especialidad]: (r[c.especialidad] ?? 0) + 1 }), {})).sort((a,b) => b[1]-a[1])[0]; return <div className="flex flex-col gap-8"><div><p className="text-xs font-semibold tracking-[0.14em] uppercase text-[#0E9668] mb-1">Panel administrativo</p><h1 className="sax-display text-3xl text-[#0F3D3E]">Resumen general</h1></div><div className="grid grid-cols-2 sm:grid-cols-4 gap-4"><StatCard icon="event" valor={citasHoy.length} etiqueta="Citas hoy" color="#0F3D3E" tinte="#EDF2F1" /><StatCard icon="check_circle" valor={conteo.completada} etiqueta="Completadas hoy" color="#48605C" tinte="#EDF2F1" /><StatCard icon="hourglass_top" valor={conteo.agendada + conteo.reprogramada} etiqueta="Pendientes hoy" color="#0E9668" tinte="#D3F3E6" /><StatCard icon="cancel" valor={conteo.cancelada} etiqueta="Canceladas hoy" color="#BA1A1A" tinte="#FFDAD6" /></div><div className="grid grid-cols-1 sm:grid-cols-3 gap-4"><StatCard icon="donut_large" valor={citas.length ? `${Math.round(activas / citas.length * 100)}%` : "0%"} etiqueta="Citas activas del total" color="#0E9668" tinte="#D3F3E6" /><StatCard icon="stethoscope" valor={medicos.filter((m) => m.activo).length} etiqueta="Médicos activos" color="#0F3D3E" tinte="#EDF2F1" /><StatCard icon="medical_information" valor={top?.[0] ?? "—"} etiqueta="Especialidad más demandada" color="#8A6D00" tinte="#F5EEDA" truncar /></div><div><div className="flex items-center justify-between mb-3"><h2 className="sax-display text-xl text-[#0F3D3E]">Citas de hoy</h2><button onClick={onIrACitas} className="text-sm font-semibold text-[#0E9668] hover:underline">Ver todas las citas →</button></div>{citasHoy.length ? <div className="flex flex-col gap-2">{citasHoy.sort((a,b) => a.hora.localeCompare(b.hora)).map((c) => <FilaCitaResumen key={c.id} cita={c} />)}</div> : <p className="text-sm text-[#48605C] bg-white border border-[#DCE8E5] rounded-xl px-4 py-3">No hay citas programadas para hoy.</p>}</div></div>; }
