import { useEffect, useMemo, useState } from "react";
import { Campo, ConfirmacionInline, EstadoBadge } from "../../context/ui";
import { cancelarCita, cargarEps, cargarEspecialidades, cargarMedicos, cargarPacientes, cargarSedes, crearCita, reprogramarCita } from "../../api/admin";
import { extraerMensajeError } from "../../api/axiosClient";

const inicio = { paciente: "", especialidad: "", medico: "", sede: "", fecha: "", hora: "", motivo: "" };
const esActiva = (cita) => ["agendada", "reprogramada"].includes(cita.estado);
const sumarMediaHora = (hora) => { const [h, m] = hora.split(":").map(Number); const total = h * 60 + m + 30; return `${String(Math.floor(total / 60) % 24).padStart(2, "0")}:${String(total % 60).padStart(2, "0")}:00`; };
export default function TabCitas({ citas, onCambio }) {
  const [vista, setVista] = useState("lista"), [filtro, setFiltro] = useState(""), [citaCancelar, setCitaCancelar] = useState(null), [citaEditar, setCitaEditar] = useState(null);
  const filtradas = useMemo(() => { const q = filtro.toLowerCase(); return citas.filter((c) => !q || `${c.pacienteNombre} ${c.medicoNombre} ${c.especialidad} ${c.fecha} ${c.estado}`.toLowerCase().includes(q)).sort((a,b) => `${b.fecha}${b.hora}`.localeCompare(`${a.fecha}${a.hora}`)); }, [citas, filtro]);
  const cancelar = async () => { try { await cancelarCita(citaCancelar.id); setCitaCancelar(null); onCambio(); } catch (e) { alert(extraerMensajeError(e, "No fue posible cancelar la cita.")); } };
  if (vista === "nueva") return <FormularioCita onCancelar={() => setVista("lista")} onGuardado={() => { setVista("lista"); onCambio(); }} />;
  if (citaEditar) return <FormularioReprogramar cita={citaEditar} onCancelar={() => setCitaEditar(null)} onGuardado={() => { setCitaEditar(null); onCambio(); }} />;
  return <div className="flex flex-col gap-6"><div className="flex items-center justify-between gap-3 flex-wrap"><div><p className="text-xs font-semibold tracking-[.14em] uppercase text-[#0E9668] mb-1">Gestión de agenda</p><h1 className="sax-display text-2xl text-[#0F3D3E]">Citas</h1></div><button onClick={() => setVista("nueva")} className="bg-[#0E9668] text-white px-5 py-2.5 rounded-full font-semibold">Agendar cita</button></div><input value={filtro} onChange={(e) => setFiltro(e.target.value)} placeholder="Buscar por paciente, médico, especialidad o fecha" className="border border-[#DCE8E5] rounded-lg px-4 py-2.5 text-sm max-w-md" />{filtradas.map((cita) => <div key={cita.id} className="bg-white border border-[#DCE8E5] rounded-xl p-4 flex items-center justify-between gap-4 flex-wrap"><div><p className="font-semibold text-[#0F3D3E]">{cita.pacienteNombre} · {cita.especialidad}</p><p className="text-sm text-[#48605C]">{cita.fecha} · {cita.hora} · Dr(a). {cita.medicoNombre} · {cita.sede}</p></div><div className="flex gap-2 items-center"><EstadoBadge estado={cita.estado}/>{esActiva(cita) && <><button onClick={() => setCitaEditar(cita)} className="text-xs border border-[#0E9668] text-[#0E9668] rounded-full px-3 py-1.5">Reprogramar</button><button onClick={() => setCitaCancelar(cita)} className="text-xs border border-[#BA1A1A] text-[#BA1A1A] rounded-full px-3 py-1.5">Cancelar</button></>}</div></div>)}{!filtradas.length && <p className="text-sm text-[#48605C]">No hay citas para mostrar.</p>}{citaCancelar && <ConfirmacionInline pregunta={`¿Cancelar la cita de ${citaCancelar.pacienteNombre}?`} textoConfirmar="Sí, cancelar" onConfirmar={cancelar} onCancelar={() => setCitaCancelar(null)} />}</div>;
}
function FormularioCita({ onCancelar, onGuardado }) {
  const [form, setForm] = useState(inicio), [pacientes, setPacientes] = useState([]), [medicos, setMedicos] = useState([]), [especialidades, setEspecialidades] = useState([]), [sedes, setSedes] = useState([]), [error, setError] = useState(""), [guardando, setGuardando] = useState(false);
  useEffect(() => { Promise.all([cargarPacientes(), cargarMedicos(), cargarEspecialidades(), cargarSedes(), cargarEps()]).then(([p,m,e,s]) => { setPacientes(p.filter((x) => x.activo)); setMedicos(m.filter((x) => x.activo)); setEspecialidades(e.filter((x) => x.activo)); setSedes(s.filter((x) => x.activo)); }).catch((e) => setError(extraerMensajeError(e, "No fue posible cargar los catálogos."))); }, []);
  const cambiar = (campo) => (e) => setForm((f) => ({ ...f, [campo]: e.target.value }));
  const enviar = async (e) => { e.preventDefault(); const paciente = pacientes.find((x) => String(x.id) === form.paciente); if (!paciente?.epsId) return setError("El paciente seleccionado no tiene una EPS asignada."); try { setGuardando(true); setError(""); await crearCita({ paciente: +form.paciente, medico: +form.medico, especialidad: +form.especialidad, sede: +form.sede, eps: paciente.epsId, fecha: form.fecha, hora_inicio: `${form.hora}:00`, hora_fin: sumarMediaHora(form.hora), motivo_consulta: form.motivo, tipo_cita: "consulta_general" }); onGuardado(); } catch (x) { setError(extraerMensajeError(x, "No fue posible agendar la cita.")); } finally { setGuardando(false); } };
  return <div className="max-w-xl bg-white border border-[#DCE8E5] rounded-2xl p-6"><h2 className="sax-display text-2xl text-[#0F3D3E] mb-5">Agendar cita</h2><form onSubmit={enviar} className="flex flex-col gap-4"><Select label="Paciente" value={form.paciente} onChange={cambiar("paciente")} items={pacientes} /><Select label="Especialidad" value={form.especialidad} onChange={cambiar("especialidad")} items={especialidades} /><Select label="Médico" value={form.medico} onChange={cambiar("medico")} items={medicos} /><Select label="Sede" value={form.sede} onChange={cambiar("sede")} items={sedes} /><div className="grid grid-cols-2 gap-4"><Campo label="Fecha" type="date" value={form.fecha} onChange={cambiar("fecha")} /><Campo label="Hora" type="time" value={form.hora} onChange={cambiar("hora")} /></div><Campo label="Motivo de consulta" value={form.motivo} onChange={cambiar("motivo")} />{error && <p className="text-sm text-[#BA1A1A]">{error}</p>}<div className="flex gap-3"><button disabled={guardando} className="bg-[#0E9668] text-white px-5 py-2.5 rounded-full">{guardando ? "Guardando…" : "Confirmar cita"}</button><button type="button" onClick={onCancelar} className="text-[#48605C]">Cancelar</button></div></form></div>;
}
function FormularioReprogramar({ cita, onCancelar, onGuardado }) { const [fecha, setFecha] = useState(cita.fecha), [hora, setHora] = useState(cita.hora), [error, setError] = useState(""); const enviar = async (e) => { e.preventDefault(); try { await reprogramarCita(cita.id, { fecha, hora_inicio: `${hora}:00`, hora_fin: sumarMediaHora(hora) }); onGuardado(); } catch (x) { setError(extraerMensajeError(x, "No fue posible reprogramar la cita.")); } }; return <div className="max-w-xl bg-white border border-[#DCE8E5] rounded-2xl p-6"><h2 className="sax-display text-2xl text-[#0F3D3E] mb-2">Reprogramar cita</h2><p className="text-sm text-[#48605C] mb-5">{cita.pacienteNombre} · Dr(a). {cita.medicoNombre}</p><form onSubmit={enviar} className="flex flex-col gap-4"><div className="grid grid-cols-2 gap-4"><Campo label="Fecha" type="date" value={fecha} onChange={(e) => setFecha(e.target.value)} /><Campo label="Hora" type="time" value={hora} onChange={(e) => setHora(e.target.value)} /></div>{error && <p className="text-sm text-[#BA1A1A]">{error}</p>}<div className="flex gap-3"><button className="bg-[#0E9668] text-white px-5 py-2.5 rounded-full">Guardar</button><button type="button" onClick={onCancelar}>Cancelar</button></div></form></div>; }
function Select({ label, value, onChange, items }) { return <label className="text-sm font-semibold text-[#0F3D3E]">{label}<select required value={value} onChange={onChange} className="mt-1 border border-[#DCE8E5] rounded-lg px-3 py-2 w-full font-normal"><option value="">Selecciona una opción</option>{items.map((item) => <option key={item.id} value={item.id}>{item.nombre ?? `${item.nombre ?? item.nombres} ${item.apellido ?? item.apellidos ?? ""}`.trim()}</option>)}</select></label>; }
